# -*- coding: utf-8 -*-
"""CA 1 Assignment .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wYklhLhUGgXmWlRIiTQVK1bgoL5VzJbs

Pradyumna Shivanandaiah

#Import Necessary Libraries For This Project
"""

import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from imblearn.over_sampling import SMOTE
from sklearn.ensemble import RandomForestClassifier
from imblearn.pipeline import Pipeline
from sklearn.svm import SVC
from pandas import read_csv, get_dummies,DataFrame,Series
from sklearn import tree

"""#Importing and reading Data Via Pandas Librarie"""

# Load the data from the CSV file
Sample_Data=read_csv('/content/drive/MyDrive/DBS/Applied_Stats_Assigenment/CA 1/CustomerChurn.csv')
#display all columns to make sure all the data is clean and ready
pd.set_option('display.max_columns', None)
print(Sample_Data.shape)
print(Sample_Data.head(3))
print(Sample_Data.describe())
print(Sample_Data.info())

"""#Encoding the data

"""

#Converting Categorical features into Numerical features

Sample_Data['Gender'] = Sample_Data['Gender'].map({'M':1, 'F':0})
Sample_Data['Attrition_Flag'] = Sample_Data['Attrition_Flag'].map({'Existing Customer':1, 'Attrited Customer':0})
#Categorical
CF_Dataset = ['Education_Level','Marital_Status','Income_Category','Card_Category']
fd = pd.get_dummies(Sample_Data, columns = CF_Dataset)
print(fd.info())
print(fd.head(2))

print(Sample_Data.info())

"""#Features , Labels And Scaling The DataSet"""

#define features and labels
X = fd.drop(['Attrition_Flag'], axis = 1) # Features
Y = fd['Attrition_Flag'] # Labels
#Scale the features via StandardScaler
feature_scaler = StandardScaler()
X_scaled = feature_scaler.fit_transform(X)
print(type(X))
print(type(Y))
print(X.shape)
print(Y.shape)

"""#Tuning The Data"""

#random forest parameter 'n_estimators'
model = Pipeline([
        ('balancing', SMOTE(random_state = 101)),
        ('classification', RandomForestClassifier(criterion='entropy', max_features='auto', random_state=1) )])
grid_param = {'classification__n_estimators': [10, 20, 50, 80, 100]}

"""Cross-Validation Using Grid Search"""

#using Grid Search for Random Forest Classifier
GridSearch = GridSearchCV(estimator=model, param_grid=grid_param, scoring='precision', cv=5) #Selecting Precision to minimize false positives
GridSearch.fit(X_scaled, Y)

best_parameters = GridSearch.best_params_
print(best_parameters)

best_result = GridSearch.best_score_ # Mean cross-validated score of the best_estimator
print(best_result)

"""Hyperparameter tuning"""

# Define the pipeline
model = Pipeline([
    ('balancing', SMOTE(random_state=101)),
    ('classification', RandomForestClassifier(criterion='entropy', max_features='auto', random_state=1))
])

# Define the parameter grid for GridSearchCV
grid_param = {
    'classification__n_estimators': [100, 150, 200, 250, 300]
}

# Create GridSearchCV object
GridSearch = GridSearchCV(estimator=model, param_grid=grid_param, scoring='precision', cv=5)

# Fit the model with GridSearchCV
GridSearch.fit(X_scaled, Y)

# Get the best parameters and best score
best_parameters = GridSearch.best_params_
print("Best Parameters:", best_parameters)

best_result = GridSearch.best_score_
print("Best Precision Score:", best_result)

"""Feature selection and feature scaling on a dataset"""

# Overfitting avoidance
# Finding the most important variables for tuning
rfc = RandomForestClassifier(n_estimators=150, criterion='entropy', max_features='auto', random_state=1)
rfc.fit(X_scaled,Y)
impfeat = pd.Series(rfc.feature_importances_, index=list(X)).sort_values(ascending=False)
print(impfeat)

"""Feature selection and classification using a random forest classifier 5 Variable

"""

# Selecting features with higher significance and redefining feature set
X2 = Sample_Data[['Total_Trans_Amt','Total_Trans_Ct','Total_Revolving_Bal', 'Total_Relationship_Count', 'Credit_Limit']]

# Scale the features using StandardScaler
feature_scaler = StandardScaler()
X_scaled = feature_scaler.fit_transform(X2)

# Define the pipeline
model = Pipeline([
    ('balancing', SMOTE(random_state=101)),
    ('classification', RandomForestClassifier(criterion='entropy', max_features='auto', random_state=1))
])

# Define the parameter grid for GridSearchCV
grid_param = {
    'classification__n_estimators': [150, 180, 200, 250]
}

# Create GridSearchCV object
GridSearch = GridSearchCV(estimator=model, param_grid=grid_param, scoring='precision', cv=5)

# Fit the model with GridSearchCV
GridSearch.fit(X_scaled, Y)

# Get the best parameters and best score
best_parameters = GridSearch.best_params_
print("Best Parameters:", best_parameters)

best_result = GridSearch.best_score_
print("Best Precision Score:", best_result)

"""#RFC with 3 Variable"""

# Selecting features with higher significance and redefining feature set
X3 = Sample_Data[['Total_Trans_Amt', 'Total_Trans_Ct', 'Total_Revolving_Bal']]

# Scale the features using StandardScaler
feature_scaler = StandardScaler()
X_scaled = feature_scaler.fit_transform(X3)

# Define the pipeline
model = Pipeline([
    ('balancing', SMOTE(random_state=101)),
    ('classification', RandomForestClassifier(criterion='entropy', max_features='auto', random_state=1))])

# Define the parameter grid for GridSearchCV
grid_param = {
    'classification__n_estimators': [150, 180, 200, 250]}

# Create GridSearchCV object
GridSearch = GridSearchCV(estimator=model, param_grid=grid_param, scoring='precision', cv=5)

# Fit the model with GridSearchCV
GridSearch.fit(X_scaled, Y)

# Get the best parameters and best score
best_parameters = GridSearch.best_params_
print("Best Parameters:", best_parameters)

best_result = GridSearch.best_score_
print("Best Precision Score:", best_result)

"""#SVC"""

# Create the pipeline
model = Pipeline([
    ('balancing', SMOTE(random_state=101)),
    ('classification', SVC(random_state=1))])

# Define the parameter grid for GridSearchCV
grid_param = {
    'classification__kernel': ['linear', 'poly', 'rbf', 'sigmoid'],
    'classification__C': [0.001, 0.01, 0.1, 1, 10, 100] }

# Create the GridSearchCV object
GridSearch = GridSearchCV(estimator=model, param_grid=grid_param, scoring='precision', cv=5)

# Fit the model with GridSearchCV
GridSearch.fit(X_scaled, Y)

# Get the best parameters and best score
best_parameters = GridSearch.best_params_
print("Best Parameters:", best_parameters)

best_result = GridSearch.best_score_
print("Best Precision Score:", best_result)